### PR TITLE
Integrating Prettier

### PR DESCRIPTION
**Pull request by mthirumalai2905**
Formatted the document with Prettier resulting in better code readability

### CODE REVIEW

**Comment by mthirumalai2905** [comment]
Please have a look into it i have formatted the document with prettier

**Review by mthirumalai2905 — COMMENTED** [review]
I have cross-checked and reviewed too

**Comment by rlabbeptc** [comment]
Thanks. I'll take a look as soon as I can.

**Comment by mthirumalai2905** [comment]
@rlabbeptc Have u checked it sir wheter its alright

**Comment by mthirumalai2905** [comment]
@rlabbeptc how's it sir

**Review by mthirumalai2905 — COMMENTED** [review]
👍

**Comment by mthirumalai2905** [comment]
Have u checked it @rlabbeptc

**Comment by rlabbeptc** [comment]
Thanks for the feedback and the formatting. Since we have not defined specific formatting requirements or tools like Prettier, I'm going to close this PR. If we decide to use prettier in the future, we'll make sure to execute the consistent formatting across the board.

**Pull request closed without merging**
